import { AuthProvider } from "./context/AuthContext";
import { GuestProvider } from "./context/GuestContext";
import NavBarWrapper from "./components/NavBarWrapper";
import { ProductsProvider } from "./context/ProductsContext";
import { CartProvider } from "./context/CartContext";
import { OrderProvider } from "./context/OrderContext";
import { NotificationProvider } from "./context/NotificationContext";
import { Toaster } from "@/components/ui/toaster";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pd-16`}
      >
        <AuthProvider>
          <GuestProvider>
            <ProductsProvider>
              <OrderProvider>
                <CartProvider>
                  <NotificationProvider>
                    {children}
                    <NavBarWrapper />
                    <Toaster />
                  </NotificationProvider>
                </CartProvider>
              </OrderProvider>
            </ProductsProvider>
          </GuestProvider>
        </AuthProvider>
      </body>
    </html>
  );
}